"""Windows restore-point creation, with explicit post-creation verification."""

import base64
from uuid import uuid4


class RestorePointError(Exception):
    pass


def restore_script(description):
    # Description is generated by us, but quote it as data nevertheless.
    quoted = description.replace("'", "''")
    return """$ErrorActionPreference = 'Stop'
try {
    $before = @(Get-ComputerRestorePoint -ErrorAction Stop)
    $recent = @($before | Where-Object {
        [System.Management.ManagementDateTimeConverter]::ToDateTime($_.CreationTime) -gt (Get-Date).AddHours(-24)
    })
    if ($recent.Count -gt 0) { exit 50 }
    $description = '""" + quoted + """'
    Checkpoint-Computer -Description $description -RestorePointType DEVICE_DRIVER_INSTALL -ErrorAction Stop -WarningAction Stop
    $verified = @(Get-ComputerRestorePoint -ErrorAction Stop | Where-Object {
        $_.Description -eq $description -and $_.SequenceNumber -notin @($before.SequenceNumber)
    })
    if ($verified.Count -eq 0) { exit 52 }
    exit 0
} catch {
    exit 51
}
"""


def create_restore_point(notify, run_powershell):
    description = f"Remote HOSAS - Before usbip-win2 - {uuid4().hex[:12]}"
    notify("Creating a Windows restore point before installing USB drivers. Administrator approval may be required; this can take a few minutes.")
    encoded = base64.b64encode(restore_script(description).encode("utf-16-le")).decode("ascii")
    script = """$ErrorActionPreference = 'Stop'
try {
    $child = Start-Process -FilePath "$PSHOME\\powershell.exe" -ArgumentList @('-NoProfile', '-NonInteractive', '-EncodedCommand', '""" + encoded + """') -Verb RunAs -WindowStyle Hidden -Wait -PassThru
    exit $child.ExitCode
} catch { exit 53 }
"""
    code = run_powershell(script, {})
    messages = {
        50: "Windows already has a restore point from the last 24 hours. No new pre-installation restore point was created.",
        51: "Windows could not create a restore point. Check that System Protection is enabled for the system drive and has enough disk space.",
        52: "Windows did not confirm a new restore point. Driver installation has not started.",
        53: "Restore-point creation could not start or administrator permission was declined.",
    }
    if code != 0:
        raise RestorePointError(messages.get(code, "Restore-point creation failed. Driver installation has not started."))
    notify(f"Restore point created and verified: {description}.")
